### ISSUE TITLE
OpenTTD 1.5 Issue

### ISSUE THREAD

**Issue by aidanmorgan** [avdg/openttd-js-api#3]
Hi,

I am really interested in using this project for something I am working on, however I have tried the latest version of OpenTTD and I can't get this to work with the latest version of OpenTTD (1.5.0).

I start a new multiplayer game, hosting the server and with a password set. When attempting to get node to connect I get the folllowing error:

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at EventEmitter.emit (events.js:74:15)
    at Socket.module.exports.tcpPacketListener.defaultOnError (C:\programming\pr
ojects\OpenTTD\Game\nodejs\lib\openttd-adminport.js:93:22)
    at Socket.emit (events.js:95:17)
    at Socket._destroy.self._writableState.errorEmitted (net.js:440:14)
    at process._tickCallback (node.js:419:13)

The code I am executing is:

var openttd = require('./openttd-js-api.js');
var client = new openttd.adminport({
    'host': 'localhost',
    'port': '3979',
    'botname': 'PollerBot',
    'password': 'password',
    'version': '0.0.1'
});

client.poll('cmd names');
client.poll("company info");

**Comment by avdg** [comment]
I will take a look at it

**Comment by avdg** [comment]
The cause seems to be that client.poll is called before a connection is opened.

**Comment by avdg** [comment]
Current workaround: replace `client.poll('cmd names')` with

```javascript
client.on('welcome', function() {
    client.poll('cmd names');
});
```

Does that workaround the issue? I would still call this a bug as there are errors that shouldn't be happening though.

**Comment by aidanmorgan** [comment]
The welcome function never seems to trigger which is why I moved my code into the authorize handler instead.

**Comment by avdg** [comment]
Yeah, I had that problem too and I have to figure out that (the code base is still pretty new and lots of bugs still have to be found). Though the code in the documentation folder works just fine...

Anyway, if you get the code working I'm happy for you :-)

**Comment by avdg** [comment]
(hmm now I don't know how to reproduce the welcome event bug...)
